#!/bin/bash
# get-volume script returns the current volume status of your system in a
# format suitable for use in xmobar. I found this script on this page:
# http://karuppuswamy.com/wordpress/2011/09/03/how-to-get-a-productive-desktop-based-on-xmonad-and-xmobar/
#
# Original author unknown -- credited to "a nice guy online". :-)
#
# Note that if this is not working for your hardware, it may be because
# you have more than one sound card. In that case you may be able to make
# it work by adding arguments to the amixer command in the first line.
# For example, the "-c N" argument makes it choose the card identified by
# N, where N is an integer. If you have two cards, try using "-c 1" to make
# it use the second card.

str=`amixer -D pulse sget Master`
str1=${str#Simple*[}
v1=`expr ${str1%%%*}`
il=`expr index "$str1" [`
o="off"
med=33
high=66
mutel=''
printf "%s%% " $v1
if [ ${str1:$il:3} == $o ]; then
  printf '\xF0\x9F\x94\x87'
elif [ $v1 -gt $high ]; then
  printf '\xF0\x9F\x94\x8A'
elif [ $v1 -gt $med ]; then
  printf '\xF0\x9F\x94\x89'
else
  printf '\xF0\x9F\x94\x88'
fi
